spring:
    application:
        name: AIRPORT-SERVICE
    boot:
        admin:
            client:
                url: http://localhost:1111

    datasource:
        url: jdbc:mariadb://67.217.240.192:3306/AirplaneBackend
        username: root
        password: rohan@2008
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true


#            properties:
#                hibernate:
#                    dialect: org.hibernate.dialect.MariaDBDialect
management:
    endpoints:
        web:
            exposure:
                include: '*'
server:
    port: 9091